name: Eleventy Build
on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  install_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run build
      - shell: bash
        run: |
        echo developers.brandmaker.com > ./_site/CNAME
      - name: Publish on published-pages
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site 
          PUBLISH_BRANCH: published-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: Pushes to another repository
      #  uses: cpina/github-action-push-to-another-repository@master
      #  env:
      #    API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #  with:
      #    source-directory: '_site'
      #    destination-github-username: 'brandmaker'
      #    destination-repository-name: 'brandmaker.github.io'
      #    user-email: meret.unbehaun@brandmaker.com
        
