name: Eleventy Build and deploy to published-pages

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Add CNAME file
        run: |
          echo developers.brandmaker.com > ./_site/CNAME

      - name: Publish on published-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: published-pages
